base_url = "https://rustunit.com"
title = "rustunit"
description = "Rustunit offers software development consulting with a focus on rust, game-development and large scale distributed backend services."

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
ru_nav = [{ name = "HOME", path = "/" }, { name = "BLOG", path = "/blog/" }]
ru_twitter = "rustunitcom"
ru_github = "https://github.com/rustunit"
ru_linkedin = "https://www.linkedin.com/company/rustunit/"
ru_mastodon = "https://mastodon.social/@rustunit"
