base_url = "https://rustunit.com"
title = "rustunit"
description = "Rustunit offers software development consulting with a focus on rust, game-development and large scale distributed backend services."
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
links = [
    # { title = "Rotterdam, NL", url = "https://maps.app.goo.gl/vYh2kSC4BPaJymXDA", iconset = "fas", icon = "location-dot" },
    { title = "Contact", url = "/contact", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com/rustunit", icon = "github" },
    # { title = "Twitter", url = "https://twitter.com/rustunitcom", icon = "twitter" },
    # { title = "LinkedIn", url = "https://www.linkedin.com/company/rustunit/", icon = "linkedin" },
    { title = "Mastodon", url = "https://mastodon.social/@rustunit", icon = "mastodon" },
]
